# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out code
    - uses: actions/checkout@v2
    # Setup JDK for build/test
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'java'        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: jar
        path: ./target/bankteller*.jar
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
